---
bibliography: ref.bib
reference-section-title: "Referências"
output: 
  pdf_document:
    includes:
      before_body: title.sty
---

\newpage

\pagenumbering{arabic}


# Objetivo

A partir de diversas técnicas de amostragem probabilística,
deseja-se obter estimativas relevantes respeito à oferta de leitos totais e
disponibilidade de leitos vinculados ao SUS em hospitais de Minas Gerais, com o objetivo de medir a capacidade hospitalar no estado.

# Universo e Unidade de Amostra

Para este estudo nos basearemos no listado pelo @datasus2026, e definimos o seguinte:

- **População de estudo:** Leitos em hospitais mineiros, durante o mês de janeiro.

- **Amostra:** Leitos de hospitais mineiros selecionados de acordo com o listado pelo DataSUS, referente ao mês de janeiro de 2026.

- **Variáveis de interesse:** Total de leitos, proporção de leitos SUS e leitos vinculados ao SUS disponíveis.

A depender do desenho amostral, pode ser relevante verificar a natureza jurídica do hospital como estrato, já que hospitais públicos e privados, filantrópicos diferem em distribuição de leitos SUS.

# Tamanho da Amostra

Para definir o tamanho de amostra consideraremos uma população de tamanho N=662 e nível de significância de 5%. Assim, tomando como referência um intervalo de confiança para a proporção de leitos sus disponíveis (não-ocupados)
